openapi: 3.0.1
info:
  title: "HackerNews"
  version: "1.0.0"
  description: "API REST de nivell 2 per a HackerNews.
  
  
  Projecte d'ASW de l'Èric Pérez, la Sufang Zhou i l'Aleix Vila"

servers:
  - url: 'http://3.236.160.83:8080'

paths:
  /api/contributions:
    get:
      tags:
      - Contributions
      description: Retorna totes les contribucions Url ordenades de més a menys puntuació.
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contribution'
  
  /api/contributions/new:
    get:
      tags:
      - Contributions
      description: Retorna totes les contribucions ordenades de més a menys recent.
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contribution'
                  
  /api/contributions/ask:
    get:
      tags:
      - Contributions
      description: Retorna totes les contribucions de tipus Ask ordenades de més a menys recent.
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contribution'
                  
  /api/contributions/{id}:
    get:
      tags:
      - Contributions
      description: Retorna la informació d'una contribució a través del seu id.
      parameters:
      - name: id
        in: path
        description: ID de la contribució a retornar.
        required: true
        schema:
          type: integer
          format: int
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contribution'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
                
  /comments/{id}:
    get:
      tags:
      - Comments
      description: Retorna la informació d'un comentari a través del seu id.
      parameters:
      - name: id
        in: path
        description: ID del comentari a retornar.
        required: true
        schema:
          type: integer
          format: int
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
   
components:
  schemas:
    Contribution:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        url:
          type: string
        text:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        points:
          type: integer
          
    Comment:
      type: object
      properties:
        id:
          type: integer
        commentText:
          type: string
        contribution:
          $ref: '#/components/schemas/Contribution'
        #Mirar com implementar users
        created_at:
          type: string
        updated_at:
          type: string
        points:
          type: integer
    
    ErrorResult:
      type: object
      properties:
        status:
          type: integer
          enum: [400, 401, 403, 404, 409]
        error: 
          type: string
          enum: ["Bad Request", "Unauthorized", "Forbidden", "Not Found", "Conflict"]
        message: 
          type: string